import type { TrainingContentResolution, TrainingExercise } from "../chess/types";
import { normalizeConceptSlug } from "../knowledge/concepts";
import BANK, { RUNTIME_BANK_MANIFEST } from "./runtime-bank.generated";
import { DECLARED_TRAINING_FALLBACKS } from "./fallbacks";

export { DECLARED_TRAINING_FALLBACKS } from "./fallbacks";

export { RUNTIME_BANK_MANIFEST };

// Generated by the existing library pipeline during the build. No chess.js
// validation, reference corpus scanning or annotation generation at startup.
const pool = BANK as unknown as TrainingExercise[];

function byAdaptedDifficulty(exercises: TrainingExercise[], userRating?: number): TrainingExercise[] {
  return exercises.toSorted((first, second) => {
    if (userRating) {
      const firstDistance = first.difficulty === undefined ? Number.MAX_SAFE_INTEGER : Math.abs(first.difficulty - userRating);
      const secondDistance = second.difficulty === undefined ? Number.MAX_SAFE_INTEGER : Math.abs(second.difficulty - userRating);
      if (firstDistance !== secondDistance) return firstDistance - secondDistance;
      const firstSlightlyHarder = Number((first.difficulty ?? 0) >= userRating);
      const secondSlightlyHarder = Number((second.difficulty ?? 0) >= userRating);
      if (firstSlightlyHarder !== secondSlightlyHarder) return secondSlightlyHarder - firstSlightlyHarder;
    }
    return (second.qualityScore ?? 0) - (first.qualityScore ?? 0) || first.id.localeCompare(second.id);
  });
}

export function conceptExercisesForSlug(conceptSlug: string, limit = 2, userRating?: number): TrainingExercise[] {
  conceptSlug = normalizeConceptSlug(conceptSlug);
  return byAdaptedDifficulty(pool.filter((exercise) => exercise.conceptSlug === conceptSlug), userRating)
    .slice(0, limit).map((exercise) => ({
      ...exercise,
      theme: exercise.conceptSlug,
      sourceLabel: "Nouvelle position · même concept",
    }));
}

export function conceptExercisesFor(
  _category: TrainingExercise["category"], conceptSlug: string, limit = 2, userRating?: number,
): TrainingExercise[] {
  return conceptExercisesForSlug(conceptSlug, limit, userRating);
}

export function resolveConceptExercises(
  conceptSlug: string,
  limit = 2,
  userRating?: number,
): { exercises: TrainingExercise[]; resolution: TrainingContentResolution } {
  const requestedConcept = normalizeConceptSlug(conceptSlug);
  const exact = conceptExercisesForSlug(requestedConcept, limit, userRating);
  if (exact.length) {
    return {
      exercises: exact,
      resolution: { requestedConcept, servedConcept: requestedConcept, relation: "exact", exerciseCount: exact.length },
    };
  }
  for (const fallback of DECLARED_TRAINING_FALLBACKS[requestedConcept] ?? []) {
    const exercises = conceptExercisesForSlug(fallback, limit, userRating);
    if (exercises.length) {
      return {
        exercises,
        resolution: { requestedConcept, servedConcept: fallback, relation: "declared_fallback", exerciseCount: exercises.length },
      };
    }
  }
  return {
    exercises: [],
    resolution: { requestedConcept, servedConcept: null, relation: "unavailable", exerciseCount: 0 },
  };
}

export function allConceptExercises(): TrainingExercise[] {
  return [...pool];
}

export function currentTrainingPool(historical: TrainingExercise[]): TrainingExercise[] {
  return [...historical.filter((exercise) => exercise.origin === "personal"), ...pool];
}
