import type { TrainingExercise } from "@/domain/chess/types";

/**
 * Small, reviewed non-tactical bank. Each entry teaches one named decision and
 * can be extended independently from the Lichess tactical import.
 */
export const STRUCTURED_TRAINING_BANK: TrainingExercise[] = [
  {
    id: "bank-strategy-worst-bishop-d3",
    type: "strategy",
    origin: "concept",
    mode: "one-move",
    theme: "improve_worst_piece",
    conceptSlug: "improve_worst_piece",
    domain: "strategy",
    primaryConcept: "improve_worst_piece",
    category: "strategy",
    title: "Rends ta pire pièce utile",
    prompt: "Quelle pièce participe le moins, et où doit-elle aller ?",
    sourceLabel: "Bibliothèque pédagogique ChessPath",
    fen: "r2q1rk1/pp1nbppp/2p1pn2/3p4/3P4/2N1PN2/PPQ1BPPP/R4RK1 w - - 2 13",
    playerColor: "white",
    bestMove: "e2d3",
    baselinePlayerCp: 20,
    acceptedConceptMoveUcis: ["e2d3"],
    phase: "middlegame",
    concept: "Le fou e2 est la pièce la moins active ; d3 lui donne une diagonale et un rôle autour du centre.",
    maxPlayerMoves: 1,
    solutionLine: ["e2d3"],
    explanation: {
      notice: "Le fou e2 est enfermé derrière ses propres pièces et influence peu le jeu.",
      focus: "Fou passif e2 et diagonale d3–h7.",
      plan: "Jouer Bd3 pour augmenter sa portée et préparer une action sur l’aile roi.",
      objective: "Faire participer la pièce la moins active avant d’ouvrir la position.",
      opponentIdea: "Les Noirs cherchent à terminer leur développement et contester le centre.",
      rule: "Sans tactique urgente, commence par identifier ta pièce qui possède le moins de cases utiles.",
    },
    planArrows: [{ from: "e2", to: "d3", color: "primary", label: "activation" }, { from: "d3", to: "h7", color: "secondary", label: "nouvelle diagonale" }],
    planSquares: [{ square: "d3", color: "primary" }, { square: "h7", color: "secondary" }],
    classificationConfidence: 0.96,
    difficulty: 1200,
    source: "chesspath_curated",
    qualityScore: 94,
    isVerified: true,
  },
  {
    id: "bank-strategy-weak-pawn-d5",
    type: "strategy",
    origin: "concept",
    mode: "one-move",
    theme: "weak_pawn",
    conceptSlug: "weak_pawn",
    domain: "strategy",
    primaryConcept: "weak_pawn",
    category: "strategy",
    title: "Fixe une faiblesse durable",
    prompt: "Quel placement commence à mettre la faiblesse adverse sous pression ?",
    sourceLabel: "Bibliothèque pédagogique ChessPath",
    fen: "r2q1rk1/pp1nbppp/5n2/3p4/3P4/2N1PN2/PPQ1BPPP/R3R1K1 w - - 2 13",
    playerColor: "white",
    bestMove: "e1d1",
    baselinePlayerCp: 15,
    acceptedConceptMoveUcis: ["e1d1", "a1d1"],
    phase: "middlegame",
    concept: "Le pion d5 n’a plus de pion voisin : la colonne d permet de le fixer puis de l’attaquer.",
    maxPlayerMoves: 1,
    solutionLine: ["e1d1"],
    explanation: {
      notice: "Le pion d5 est isolé : aucun pion voisin ne peut le soutenir.",
      focus: "Pion faible d5 et colonne d.",
      plan: "Placer une tour sur d1, fixer d5 puis ajouter une seconde pièce à l’attaque.",
      objective: "Forcer les pièces noires à défendre passivement une faiblesse durable.",
      opponentIdea: "Les Noirs veulent avancer d5–d4 ou échanger ce pion avant qu’il ne devienne une cible.",
      rule: "Fixe d’abord un pion faible, puis attaque-le avec plus de pièces qu’il n’a de défenseurs.",
    },
    planArrows: [{ from: "e1", to: "d1", color: "primary", label: "tour sur la colonne" }, { from: "d1", to: "d5", color: "secondary", label: "cible" }],
    planSquares: [{ square: "d5", color: "warning" }],
    classificationConfidence: 0.95,
    difficulty: 1300,
    source: "chesspath_curated",
    qualityScore: 95,
    isVerified: true,
  },
  {
    id: "bank-strategy-minority-break-b4",
    type: "strategy",
    origin: "concept",
    mode: "one-move",
    theme: "pawn_break",
    conceptSlug: "pawn_break",
    domain: "strategy",
    primaryConcept: "pawn_break",
    category: "strategy",
    title: "Prépare la bonne rupture",
    prompt: "Quelle poussée change la structure en créant une cible concrète ?",
    sourceLabel: "Bibliothèque pédagogique ChessPath",
    fen: "r2q1rk1/pp1nbppp/2p1pn2/3p4/3P4/2N1PN2/PPQ1BPPP/R3R1K1 w - - 2 13",
    playerColor: "white",
    bestMove: "b2b4",
    baselinePlayerCp: 5,
    acceptedConceptMoveUcis: ["b2b4"],
    phase: "middlegame",
    concept: "La poussée b4 attaque la base c6 et prépare une cible sur l’aile dame.",
    maxPlayerMoves: 1,
    solutionLine: ["b2b4"],
    explanation: {
      notice: "La structure noire c6–d5 possède une base attaquable sur c6.",
      focus: "Rupture b4–b5 contre le pion c6.",
      plan: "Jouer b4, poursuivre par b5 au bon moment et ouvrir une colonne contre c6.",
      objective: "Créer une faiblesse durable sur l’aile dame sans affaiblir le centre.",
      opponentIdea: "Les Noirs peuvent chercher ...a5 ou ...dxc4 pour modifier la structure avant b5.",
      rule: "Une rupture est utile lorsque tes pièces sont mieux placées que celles de l’adversaire pour exploiter les lignes ouvertes.",
    },
    planArrows: [{ from: "b2", to: "b4", color: "primary", label: "rupture" }, { from: "b4", to: "b5", color: "secondary", label: "pression sur c6" }],
    planSquares: [{ square: "c6", color: "warning" }],
    classificationConfidence: 0.95,
    difficulty: 1450,
    source: "chesspath_curated",
    qualityScore: 96,
    isVerified: true,
  },
  {
    id: "bank-endgame-king-activity",
    type: "endgame",
    origin: "concept",
    mode: "playout",
    theme: "king_activity",
    conceptSlug: "king_activity",
    domain: "endgame",
    primaryConcept: "king_activity",
    category: "endgame",
    title: "Active le roi avant les pions",
    prompt: "Quel trajet donne au roi le rôle le plus actif ?",
    sourceLabel: "Bibliothèque pédagogique ChessPath",
    fen: "8/5pk1/6p1/8/8/5P2/5KPP/8 w - - 0 1",
    playerColor: "white",
    bestMove: "f2e3",
    baselinePlayerCp: 0,
    phase: "endgame",
    concept: "Le roi doit se centraliser avant que la structure ne se fixe.",
    maxPlayerMoves: 3,
    solutionLine: ["f2e3", "g7f6", "e3d4", "f6e6", "d4c5"],
    successThresholdCp: -80,
    planArrows: [{ from: "f2", to: "e3", color: "primary", label: "centralisation" }, { from: "e3", to: "d4", color: "secondary", label: "trajet" }],
    planSquares: [{ square: "d4", color: "primary" }],
    classificationConfidence: 0.97,
    difficulty: 1050,
    source: "chesspath_curated",
    qualityScore: 95,
    isVerified: true,
  },
  {
    id: "bank-endgame-rule-square",
    type: "endgame",
    origin: "concept",
    mode: "line",
    theme: "rule_of_square",
    conceptSlug: "rule_of_square",
    domain: "endgame",
    primaryConcept: "rule_of_square",
    category: "endgame",
    title: "Entre dans le carré",
    prompt: "Le roi peut-il encore rattraper le pion ? Trouve son trajet.",
    sourceLabel: "Bibliothèque pédagogique ChessPath",
    fen: "7k/8/P7/8/8/8/4K3/8 b - - 0 1",
    playerColor: "black",
    bestMove: "h8g7",
    baselinePlayerCp: 0,
    phase: "endgame",
    concept: "Le roi noir entre dans le carré du pion avant sa prochaine poussée.",
    maxPlayerMoves: 2,
    solutionLine: ["h8g7", "a6a7", "g7f6"],
    planArrows: [{ from: "h8", to: "g7", color: "primary", label: "entrée dans le carré" }, { from: "g7", to: "f6", color: "secondary", label: "rattraper" }],
    planSquares: [{ square: "g7", color: "primary" }, { square: "a8", color: "warning" }],
    classificationConfidence: 0.99,
    difficulty: 850,
    source: "chesspath_curated",
    qualityScore: 97,
    isVerified: true,
  },
  {
    id: "bank-conversion-simplify-queens",
    type: "conversion",
    origin: "concept",
    mode: "line",
    theme: "simplify_when_ahead",
    conceptSlug: "simplify_when_ahead",
    domain: "conversion",
    primaryConcept: "simplify_when_ahead",
    category: "conversion",
    title: "Simplifie sans rendre l’avantage",
    prompt: "Quel échange réduit le contre-jeu tout en gardant ton matériel de plus ?",
    sourceLabel: "Bibliothèque pédagogique ChessPath",
    fen: "3q1rk1/5ppp/8/8/8/8/5PPP/3QRRK1 w - - 0 1",
    playerColor: "white",
    bestMove: "d1d8",
    baselinePlayerCp: 650,
    phase: "middlegame",
    concept: "L’échange des dames supprime les menaces contre le roi et laisse deux tours contre une.",
    maxPlayerMoves: 2,
    solutionLine: ["d1d8", "f8d8", "e1e8"],
    successThresholdCp: 400,
    planArrows: [{ from: "d1", to: "d8", color: "primary", label: "échange des dames" }, { from: "e1", to: "e8", color: "secondary", label: "activité après l’échange" }],
    planSquares: [{ square: "d8", color: "warning" }],
    classificationConfidence: 0.98,
    difficulty: 1150,
    source: "chesspath_curated",
    qualityScore: 96,
    isVerified: true,
  },
  {
    id: "bank-opening-central-break-d4",
    type: "opening",
    origin: "concept",
    mode: "one-move",
    theme: "center_control",
    conceptSlug: "center_control",
    domain: "opening",
    primaryConcept: "center_control",
    category: "opening",
    title: "Joue la rupture centrale au bon moment",
    prompt: "Ton roi est en sécurité et tes pièces sont sorties : comment contester le centre ?",
    sourceLabel: "Bibliothèque pédagogique ChessPath",
    fen: "r1bq1rk1/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQ1RK1 w - - 6 6",
    playerColor: "white",
    bestMove: "d2d4",
    baselinePlayerCp: 30,
    phase: "opening",
    concept: "La poussée d4 conteste immédiatement e5 et profite du développement déjà terminé.",
    maxPlayerMoves: 1,
    solutionLine: ["d2d4"],
    planArrows: [{ from: "d2", to: "d4", color: "primary", label: "rupture centrale" }, { from: "d4", to: "e5", color: "secondary", label: "pression centrale" }],
    planSquares: [{ square: "e5", color: "warning" }],
    classificationConfidence: 0.97,
    difficulty: 1250,
    source: "chesspath_curated",
    qualityScore: 95,
    isVerified: true,
  },
];
