import type { TrainingExercise } from "@/domain/chess/types";

/**
 * Small theoretical complement for rare named positions. Root results and
 * moves were checked against the public Lichess seven-piece tablebase. The
 * master-game seed remains the source of variety; these entries teach exact
 * techniques whose defining geometry matters more than volume.
 */
export const THEORETICAL_ENDGAME_BANK: TrainingExercise[] = [
  {
    id: "tablebase-lucena-build-bridge",
    type: "endgame",
    origin: "concept",
    mode: "line",
    theme: "lucena",
    conceptSlug: "lucena",
    category: "endgame",
    domain: "endgame",
    primaryConcept: "lucena",
    title: "Construis le pont de Lucena",
    prompt: "Ton roi est devant le pion : comment préparer l'abri contre les échecs latéraux ?",
    sourceLabel: "Finale théorique · vérifiée par tablebase Lichess",
    fen: "4K3/4P1k1/8/8/8/8/7r/R7 w - - 0 1",
    playerColor: "white",
    bestMove: "a1a4",
    baselinePlayerCp: 900,
    acceptedConceptMoveUcis: ["a1a4", "a1d1", "a1e1", "a1g1"],
    phase: "endgame",
    concept: "La tour monte pour construire un pont et couper les échecs latéraux.",
    maxPlayerMoves: 4,
    solutionLine: ["a1a4"],
    successThresholdCp: 450,
    planArrows: [
      { from: "a1", to: "a4", color: "primary", label: "construire le pont" },
      { from: "e7", to: "e8", color: "secondary", label: "promouvoir" },
    ],
    planSquares: [{ square: "a4", color: "primary" }, { square: "e8", color: "secondary" }],
    classificationConfidence: 1,
    difficulty: 1650,
    source: "lichess_tablebase",
    sourceId: "lucena-e-file",
    verificationSource: "Lichess tablebase · win · DTZ 9",
    tablebaseWdl: "win",
    qualityScore: 100,
    isVerified: true,
  },
  {
    id: "tablebase-philidor-third-rank",
    type: "endgame",
    origin: "concept",
    mode: "line",
    theme: "philidor",
    conceptSlug: "philidor",
    category: "endgame",
    domain: "endgame",
    primaryConcept: "philidor",
    title: "Tiens la troisième rangée",
    prompt: "Comment empêcher le roi adverse d'avancer avant de donner des échecs par derrière ?",
    sourceLabel: "Finale théorique · vérifiée par tablebase Lichess",
    fen: "4k3/8/7r/4K3/4P3/8/8/R7 b - - 0 1",
    playerColor: "black",
    bestMove: "h6b6",
    baselinePlayerCp: 0,
    acceptedConceptMoveUcis: ["h6b6", "h6c6", "h6g6"],
    phase: "endgame",
    concept: "La tour reste sur la sixième rangée pour interdire l'avancée du roi, puis donnera des échecs par derrière après la poussée du pion.",
    maxPlayerMoves: 4,
    solutionLine: ["h6b6"],
    successThresholdCp: -80,
    planArrows: [
      { from: "h6", to: "b6", color: "primary", label: "barrière latérale" },
      { from: "b6", to: "b1", color: "secondary", label: "échecs par derrière" },
    ],
    planSquares: [{ square: "e6", color: "warning" }, { square: "b6", color: "primary" }],
    classificationConfidence: 1,
    difficulty: 1600,
    source: "lichess_tablebase",
    sourceId: "philidor-e-file",
    verificationSource: "Lichess tablebase · draw",
    tablebaseWdl: "draw",
    qualityScore: 100,
    isVerified: true,
  },
];
