import type { PilotConceptContract, PilotConceptId } from "./types";

const sharedCounterfactualPolicy = {
  allowed: [
    "position naturelle avant/après un événement traçable",
    "branche légale depuis la même position",
    "transformation synthétique contrôlée en dernier recours",
  ],
  required_checks: [
    "légalité de la position et des coups",
    "plausibilité échiquéenne",
    "absence de nouvelle tactique cachée",
    "conservation des variables non causales",
    "marquage explicite synthetic=true lorsque nécessaire",
  ],
  forbidden: ["créer un exercice Training", "inventer une source", "utiliser le score moteur comme label conceptuel"],
} as const;

const sharedInvariancePolicy = {
  allowed: ["aile opposée", "source différente", "structure éloignée", "symétrie légale", "matériel non causal"],
  required_checks: ["mécanisme causal inchangé", "même unité d’analyse", "pas de tactique dominante ajoutée"],
  forbidden: ["modifier la variable constitutive", "supposer qu’une symétrie change le trait"],
} as const;

const sharedHoldoutPolicy = {
  development_only: true as const,
  forbidden_split_leakage: [
    "même partie", "positions proches en plies", "même joueur", "même structure",
    "même PV", "même contre-factuel", "même générateur synthétique", "symétrie proche",
  ],
  future_independent_requirements: [
    "collection non déclenchée par le détecteur ChessPath",
    "double annotation aveugle selon le contrat versionné",
    "adjudication des désaccords sans consulter la prédiction",
    "gel des clusters et labels avant l’évaluation du Pattern Engine",
  ],
};

const common = {
  version: "1.0.0-pilot" as const,
  counterfactual_policy: { ...sharedCounterfactualPolicy, allowed: [...sharedCounterfactualPolicy.allowed], required_checks: [...sharedCounterfactualPolicy.required_checks], forbidden: [...sharedCounterfactualPolicy.forbidden] },
  invariance_policy: { ...sharedInvariancePolicy, allowed: [...sharedInvariancePolicy.allowed], required_checks: [...sharedInvariancePolicy.required_checks], forbidden: [...sharedInvariancePolicy.forbidden] },
  holdout_policy: sharedHoldoutPolicy,
};

export const PILOT_CONCEPT_CONTRACTS: Record<PilotConceptId, PilotConceptContract> = {
  outpost: {
    ...common,
    concept_id: "outpost",
    annotation_scope: ["position", "move", "short_sequence"],
    minimal_definition: "Case avancée stable qu’une pièce peut réellement atteindre et depuis laquelle elle remplit un rôle utile sans pouvoir être chassée favorablement par un pion.",
    object_type: "functional_relation",
    mechanism_families: [
      { id: "install", sufficient_conditions: ["case stable", "route réaliste", "pièce installable"], expected_affordances: ["cibles ou restriction depuis la case"], failure_modes: ["trajet trop lent", "échange immédiat favorable à l’adversaire"] },
      { id: "maintain", sufficient_conditions: ["pièce déjà installée", "case non chassable"], expected_affordances: ["rôle durable"], failure_modes: ["pièce décorative", "urgence ailleurs"] },
      { id: "prevent_enemy", sufficient_conditions: ["avant-poste adverse accessible", "action préventive légale"], expected_affordances: ["route ou support supprimé"], failure_modes: ["case forte sans pièce capable de l’utiliser"] },
    ],
    constitutive_conditions: ["case dans le camp adverse ou fonctionnellement avancée", "absence de chasse favorable par pion", "accès plausible", "rôle après installation"],
    supporting_evidence: ["support par pion", "cibles concrètes", "restriction d’une pièce", "gain d’activité durable"],
    disqualifiers: ["pion adverse peut chasser avec gain de temps", "route tactiquement impossible", "échange immédiat annule le rôle", "aucune fonction après arrivée"],
    confounders: ["fourchette tactique", "case centrale visuellement attractive", "cavalier déjà avancé", "gain de matériel immédiat"],
    neighboring_concepts: ["weak_square", "improve_worst_piece", "piece_activity", "restrict_counterplay"],
    presence_criteria: ["identifier séparément outpost_square, reachable_outpost, installed_outpost et effective_outpost"],
    affordance_criteria: ["route praticable à coût acceptable", "au moins une cible, restriction ou case de transit utile"],
    decision_relevance_criteria: ["installer, conserver ou empêcher l’avant-poste change les plans plausibles"],
    centrality_evidence: ["le bénéfice du coup disparaît si la stabilité ou les cibles sont retirées", "pas de tactique dominante"],
    uncertainty_conditions: ["chasse par pion possible mais structure instable", "route de plusieurs temps", "échange ambigu"],
    pedagogical_priority_criteria: ["erreur humaine plausible", "mécanisme transférable", "contraste clair avec une case seulement esthétique"],
    training_suitability_criteria: ["destination et rôle explicables", "alternative humaine plausible", "plusieurs coups équivalents acceptés"],
    known_boundary_cases: ["avant-poste temporaire utile tactiquement", "case forte mais inaccessible", "avant-poste échangeable contre le bon défenseur"],
    known_expert_disagreement_cases: ["valeur d’un avant-poste sans cible directe", "coût acceptable d’une manœuvre de trois temps"],
    causal_flip_policy: { ...sharedCounterfactualPolicy, allowed: ["ajouter/restaurer un pion pouvant chasser", "couper la route", "retirer toutes les cibles"], required_checks: ["presence de la case peut rester stable quand seule l’affordance change", "aucune tactique créée"], forbidden: ["déplacer arbitrairement plusieurs pièces"] },
    shortcuts_under_test: ["knight_on_d5 = outpost", "advanced_knight = outpost", "central_square = outpost"],
  },
  open_file: {
    ...common,
    concept_id: "open_file",
    annotation_scope: ["position", "move", "short_sequence"],
    minimal_definition: "Colonne sans pion dont l’accès par une tour ou une dame crée une entrée, une cible, une contention ou une invasion réellement utile.",
    object_type: "static_property",
    mechanism_families: [
      { id: "occupy", sufficient_conditions: ["colonne ouverte", "accès légal"], expected_affordances: ["case d’entrée ou cible"], failure_modes: ["aucune entrée", "tour requise ailleurs"] },
      { id: "contest", sufficient_conditions: ["colonne occupée par l’adversaire", "échange ou contestation possible"], expected_affordances: ["réduction de l’activité adverse"], failure_modes: ["échange de la bonne tour adverse"] },
      { id: "prepare_entry", sufficient_conditions: ["colonne ouverte", "entrée encore bloquée"], expected_affordances: ["création d’une case d’invasion"], failure_modes: ["préparation trop lente"] },
    ],
    constitutive_conditions: [
      "aucun pion sur la colonne pour open_file_exists",
      "pièce lourde candidate identifiée",
      "accès légal séparé de la simple présence",
      "relation explicite entre colonne et décision lorsque relevance > 0",
    ],
    supporting_evidence: ["tour pouvant accéder", "case d’entrée sûre", "cible fixe", "possibilité de doubler ou contester"],
    disqualifiers: ["colonne seulement visuellement ouverte", "aucune pièce lourde accessible", "aucune entrée ni cible", "tour défensive indispensable ailleurs"],
    confounders: ["capture tactique sur la colonne", "semi-ouverture sans cible", "gain de tempo indépendant de la colonne"],
    neighboring_concepts: ["rook_activity", "weak_pawn", "restrict_counterplay", "favorable_exchange"],
    presence_criteria: ["open_file_exists dépend seulement de la structure", "la leçon exige des axes séparés"],
    affordance_criteria: ["open_file_accessible", "entry_square_available ou target_available"],
    decision_relevance_criteria: ["occuper, contester ou préparer la colonne améliore une décision humaine plausible"],
    centrality_evidence: ["l’avantage du plan chute quand l’entrée ou la cible est supprimée"],
    uncertainty_conditions: ["entrée tactiquement instable", "deux colonnes équivalentes", "tour surchargée défensivement"],
    pedagogical_priority_criteria: ["leçon plus précise que activité générale", "contraste avec colonne sans but"],
    training_suitability_criteria: ["colonne, tour, entrée et cible nommables", "alternative naturelle identifiable"],
    known_boundary_cases: ["colonne semi-ouverte", "sacrifice d’échange sur case d’entrée", "colonne ouverte mais échange des tours favorable à l’autre camp"],
    known_expert_disagreement_cases: ["choix entre deux colonnes", "valeur d’une pénétration sans cible immédiate"],
    causal_flip_policy: { ...sharedCounterfactualPolicy, allowed: ["restaurer un pion sur la colonne", "retirer toutes les entrées", "retirer seulement la cible"], required_checks: ["distinguer baisse de presence et baisse d’affordance", "conserver les autres lignes"], forbidden: ["assimiler semi-ouverte et ouverte sans annotation"] },
    shortcuts_under_test: ["rook + pawnless_file = open_file lesson", "file_exists = central_plan"],
  },
  improve_worst_piece: {
    ...common,
    concept_id: "improve_worst_piece",
    annotation_scope: ["position", "move", "short_sequence"],
    minimal_definition: "Redéploiement réaliste de la pièce dont la contribution nette est la plus faible vers un rôle sensiblement plus utile, sans négliger une urgence supérieure.",
    object_type: "plan_intention",
    mechanism_families: [
      { id: "activate_minor", sufficient_conditions: ["pièce mineure réellement passive", "destination fonctionnelle"], expected_affordances: ["nouvelle cible, défense ou contrôle"], failure_modes: ["mobilité cosmétique"] },
      { id: "reroute_rook", sufficient_conditions: ["tour sans rôle", "route sûre"], expected_affordances: ["colonne, rangée ou défense utile"], failure_modes: ["abandon d’une tâche défensive"] },
      { id: "maneuver", sufficient_conditions: ["route de plusieurs temps stable"], expected_affordances: ["rôle final identifiable"], failure_modes: ["contre-jeu trop rapide"] },
    ],
    constitutive_conditions: ["comparaison de contribution entre pièces", "route légale plausible", "destination avec fonction", "absence d’urgence dominante"],
    supporting_evidence: ["faible activité utile", "absence de cible actuelle", "gain de coordination", "plan stable"],
    disqualifiers: ["pièce défensive essentielle", "route impossible", "destination sans fonction", "tactique urgente"],
    confounders: ["mobilité brute faible", "développement d’ouverture", "coup esthétique", "gain de tempo tactique"],
    neighboring_concepts: ["piece_activity", "outpost", "open_file", "king_activity"],
    presence_criteria: ["une pire pièce relative doit être identifiable avec son rôle actuel"],
    affordance_criteria: ["itinéraire et contribution finale réalisables au rythme de la position"],
    decision_relevance_criteria: ["le redéploiement concurrence réellement les autres plans humains"],
    centrality_evidence: ["le rôle final explique l’essentiel du bénéfice, pas un effet tactique collatéral"],
    uncertainty_conditions: ["deux pièces pareillement passives", "rôle défensif invisible à l’heuristique", "route longue"],
    pedagogical_priority_criteria: ["pièce, problème, route, destination et rôle peuvent être explicités"],
    training_suitability_criteria: ["au moins une alternative naturelle", "jalon observable", "temps de manœuvre compatible avec le niveau"],
    known_boundary_cases: ["pièce peu mobile mais bonne défensive", "amélioration par échange plutôt que déplacement", "roi comme pire pièce"],
    known_expert_disagreement_cases: ["contribution prophylactique d’une pièce", "choix entre deux redéploiements lents"],
    causal_flip_policy: { ...sharedCounterfactualPolicy, allowed: ["rendre la pièce défensive indispensable", "bloquer la route", "retirer le rôle de destination"], required_checks: ["mobilité superficielle conservée quand possible", "urgence tactique inchangée"], forbidden: ["déclarer la pièce pire par mobilité seule"] },
    shortcuts_under_test: ["low_mobility = worst_piece", "long_maneuver = improvement", "centralization = useful_role"],
  },
  opposition: {
    ...common,
    concept_id: "opposition",
    annotation_scope: ["theoretical_state", "move", "short_sequence"],
    minimal_definition: "Relation de rois, du trait et des tempi qui contrôle les cases clés et change le résultat ou la méthode d’une finale de pions.",
    object_type: "theoretical_state",
    mechanism_families: [
      { id: "direct", sufficient_conditions: ["rois alignés à une case d’intervalle", "trait pertinent"], expected_affordances: ["gain d’une case clé"], failure_modes: ["tempo de pion disponible"] },
      { id: "distant", sufficient_conditions: ["géométrie distante correcte", "parité des tempi"], expected_affordances: ["conversion en opposition directe"], failure_modes: ["débordement"] },
      { id: "reserve_tempo", sufficient_conditions: ["coup de réserve"], expected_affordances: ["transfert du trait"], failure_modes: ["tempo change la structure"] },
    ],
    constitutive_conditions: ["finale de pions pertinente", "trait", "géométrie", "cases clés", "conséquence théorique"],
    supporting_evidence: ["Syzygy WDL/DTZ lorsque applicable", "route forcée", "absence de débordement adverse"],
    disqualifiers: ["rois alignés sans conséquence", "autre pièce présente et dominante", "tempo de réserve annule la méthode", "course de pions prioritaire"],
    confounders: ["king_activity", "zugzwang", "rule_of_square", "passed_pawn"],
    neighboring_concepts: ["king_and_pawn", "king_activity", "rule_of_square", "zugzwang"],
    presence_criteria: ["opposition_geometry et effective_opposition sont annotées séparément"],
    affordance_criteria: ["les cases clés obtenues ou refusées doivent être nommables"],
    decision_relevance_criteria: ["changer le trait ou la géométrie change la route ou le résultat"],
    centrality_evidence: ["tablebase ou analyse exhaustive relie la méthode au résultat"],
    uncertainty_conditions: ["plus de sept pièces sans tablebase", "plusieurs tempi de pions", "opposition oblique"],
    pedagogical_priority_criteria: ["la conséquence pratique est plus centrale que la simple activité du roi"],
    training_suitability_criteria: ["ligne assez courte", "résultat vérifiable", "cases clés explicables"],
    known_boundary_cases: ["opposition géométrique mais mauvais côté du pion", "tempo de réserve", "bord de l’échiquier et pat"],
    known_expert_disagreement_cases: ["nommer opposition une route surtout expliquée par les cases clés"],
    causal_flip_policy: { ...sharedCounterfactualPolicy, allowed: ["changer le trait", "ajouter un tempo de pion naturel", "ouvrir une route de débordement"], required_checks: ["valider WDL si <=7 pièces", "géométrie explicitée avant/après"], forbidden: ["conclure depuis rois face à face seuls"] },
    shortcuts_under_test: ["kings_face_each_other = opposition", "pawn_endgame = opposition", "central king = opposition"],
  },
  restrict_counterplay: {
    ...common,
    concept_id: "restrict_counterplay",
    annotation_scope: ["move", "short_sequence"],
    minimal_definition: "Action qui réduit une ressource adverse viable et importante de façon stable, à un coût acceptable, avant ou pendant la réalisation de son propre plan.",
    object_type: "plan_intention",
    mechanism_families: [
      { id: "stop_break", sufficient_conditions: ["rupture adverse viable", "action qui la neutralise"], expected_affordances: ["temps pour convertir ou améliorer"], failure_modes: ["autre rupture équivalente"] },
      { id: "cut_piece_or_king", sufficient_conditions: ["route adverse active", "barrière stable"], expected_affordances: ["réduction d’activité"], failure_modes: ["barrière contournable"] },
      { id: "remove_resource", sufficient_conditions: ["ressource concrète", "échange, contrôle ou blocage"], expected_affordances: ["contre-jeu mesurablement réduit"], failure_modes: ["ressource n’était pas viable"] },
    ],
    constitutive_conditions: ["opponent_resource_before", "resource_viability", "restricting_action", "resource_after réduit", "coût acceptable"],
    supporting_evidence: ["réponse critique empêchée", "mobilité ou rupture retirée", "stabilité sur plusieurs réponses"],
    disqualifiers: ["ressource adverse imaginaire", "coup calme sans cible", "autre ressource équivalente", "coût stratégique supérieur"],
    confounders: ["prophylaxis", "defensive_resource", "simplify_when_ahead", "quiet best move"],
    neighboring_concepts: ["prophylaxis", "defensive_resource", "simplify_when_ahead", "exchange_attacker"],
    presence_criteria: ["une ressource adverse doit être explicitement annotée avant le coup"],
    affordance_criteria: ["la ressource est viable et sa restriction libère un plan ou stabilise l’avantage"],
    decision_relevance_criteria: ["le coup perd une part importante de sa justification si la ressource est supprimée"],
    centrality_evidence: ["causal flip: sans la ressource adverse, un autre plan devient équivalent ou meilleur"],
    uncertainty_conditions: ["ressources multiples", "restriction temporaire", "coût lent difficile à évaluer"],
    pedagogical_priority_criteria: ["ressource et réponse nommables", "erreur typique = poursuivre son plan trop tôt"],
    training_suitability_criteria: ["alternative humaine expose la ressource", "au moins une réponse critique", "pas de tactique dominante"],
    known_boundary_cases: ["prophylaxie sans avantage", "défense directe", "restriction d’une ressource déjà mauvaise"],
    known_expert_disagreement_cases: ["importance pratique d’un contre-jeu objectivement insuffisant", "coût acceptable de la restriction"],
    causal_flip_policy: { ...sharedCounterfactualPolicy, allowed: ["supprimer la ressource adverse", "ajouter une ressource alternative", "augmenter le coût de la restriction"], required_checks: ["le coup peut rester bon mais la centralité doit chuter", "stabilité contre réponses critiques"], forbidden: ["utiliser seulement la baisse du nombre de coups légaux"] },
    shortcuts_under_test: ["quiet_move = prophylaxis", "low_reply_count = restrict_counterplay", "best_move = restriction"],
  },
  exchange_attacker: {
    ...common,
    concept_id: "exchange_attacker",
    annotation_scope: ["move", "short_sequence"],
    minimal_definition: "Échange ou élimination de la pièce qui porte une part essentielle de l’attaque, produisant une baisse nette et durable du danger malgré le coût de l’échange.",
    object_type: "decision_comparison",
    mechanism_families: [
      { id: "forced_exchange", sufficient_conditions: ["attaquant essentiel", "échange réalisable"], expected_affordances: ["attaque neutralisée"], failure_modes: ["attaquant remplacé"] },
      { id: "offer_exchange", sufficient_conditions: ["proposition d’échange crédible", "retrait coûteux pour l’adversaire"], expected_affordances: ["initiative réduite"], failure_modes: ["échange refusé avec gain de temps"] },
      { id: "trade_defender_for_attacker", sufficient_conditions: ["coût défensif acceptable", "attaquant central"], expected_affordances: ["état défensif amélioré"], failure_modes: ["mauvaise pièce défensive cédée"] },
    ],
    constitutive_conditions: ["attaquant identifié", "rôle dans l’attaque", "échange possible", "attaque restante réduite", "coût évalué"],
    supporting_evidence: ["menaces disparaissent", "nombre d’attaquants utiles baisse", "roi ou cible peut se stabiliser"],
    disqualifiers: ["capture tactique sans lien", "attaquant secondaire", "attaque inchangée", "remplacement immédiat"],
    confounders: ["remove_defender", "favorable_exchange", "simplification_to_hold", "free_capture"],
    neighboring_concepts: ["defensive_resource", "simplification_to_hold", "favorable_exchange", "remove_defender"],
    presence_criteria: ["la pièce doit être un attaquant fonctionnel avant l’échange"],
    affordance_criteria: ["l’échange est légal, matériellement soutenable et réduit l’attaque"],
    decision_relevance_criteria: ["défendre passivement ou échanger une autre pièce laisse davantage de danger"],
    centrality_evidence: ["state change défensif lié à la disparition de l’attaquant, non au gain matériel"],
    uncertainty_conditions: ["attaque diffuse", "plusieurs attaquants interchangeables", "sacrifice complexe"],
    pedagogical_priority_criteria: ["attaquant, menace et état après échange explicables"],
    training_suitability_criteria: ["alternative défensive humaine", "suite assez courte pour constater la baisse de danger"],
    known_boundary_cases: ["capture forcée d’une pièce donnant échec", "échange de dames", "attaquant contre défenseur clé"],
    known_expert_disagreement_cases: ["importance relative de l’attaquant", "échange matériellement défavorable mais défensivement nécessaire"],
    causal_flip_policy: { ...sharedCounterfactualPolicy, allowed: ["retirer la menace portée par l’attaquant", "ajouter un attaquant de remplacement", "changer le coût de l’échange"], required_checks: ["attaque avant/après explicitée", "capture tactique dominante exclue"], forbidden: ["exchange = exchange_attacker"] },
    shortcuts_under_test: ["capture = exchange_attacker", "exchange = defense", "queen_trade = attack neutralized"],
  },
};
